DROP TABLE IF EXISTS notes CASCADE;

-- CREATE USERS
CREATE TABLE notes (
  id SERIAL PRIMARY KEY,
  application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE NOT NULL,
  body VARCHAR(1000) NOT NULL,
  date_created TIMESTAMP DEFAULT NOW()
);